### ISSUE TITLE
Get changes/submit changes menu item do not appear

### ISSUE THREAD

**Issue by asiboro** [tarombo/Tarombo-app#19]
I have this repo shown in the app: https://github.com/asiboro/tarombo-Txbro-20240430104629
It is shown as "2 di depan, 131 di belakang", which correspond with the forked repo being "2 commits ahead, 131 commits behind". In this condition, tapping on 3-dot menu on it at Trees screen should show get changes/submit changes menu items, but they do not appear.

**Comment by dadanglukisnyo** [comment]
I recognize that the popup menu is scrollable. Sometime the menus in the bottom not directly visible and need to be scrolled first.
Please confirm that this is the case.

![image](https://github.com/tarombo/Tarombo-app/assets/167685584/868c6f35-8b5f-4817-a020-62afe8ffc581)

**Comment by asiboro** [comment]
> I recognize that the popup menu is scrollable. Sometime the menus in the bottom not directly visible and need to be scrolled first. Please confirm that this is the case.
> 
> ![image](https://private-user-images.githubusercontent.com/167685584/336526619-868c6f35-8b5f-4817-a020-62afe8ffc581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODA5NjYsIm5iZiI6MTcxNzU4MDY2NiwicGF0aCI6Ii8xNjc2ODU1ODQvMzM2NTI2NjE5LTg2OGM2ZjM1LThiNWYtNDgxNy1hMDIwLTYyYWZlOGZmYzU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwOTQ0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODU0ODFiZmRlZTY1ZTM3NDJkYzQ3ODMxODM4NjFiZjBlODVlZjA5YzFiY2Y1OTJlMTU2MjA2Y2NjNmU3MjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3oNdAS-YmkbH-JuTDzHJRp4oZamsFdT2Uevv1h6X3Hs)

Oh sorry, yes that's the case.
